'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SimpleParseTXT.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to AVCScenarioInfo@@ NAME DESC BRIEFING DEBUNKW+DEBUNKW2+DEBUNKW3+DEBUNKW4+DEBUNKW5 DEBUNKL BRIEFLONG1+BRIEFLONG2+BRIEFLONG3+BRIEFLONG4+BRIEFLONG5 CREATOR
        '''AVCMidPlayer@@ NAME_TXT
        '''AVCCapital@@ NAME_TXT
        '''AVCMidVillage@@ NAME_TXT
        '''AVCMidRuin@@ TITLE
        '''AVCMidLandmark@@ DESC_TXT
        '''AVCMidSiteMerchant@@ TXT_TITLE TXT_DESC
        '''AVCMidSiteMage@@ TXT_TITLE TXT_DESC
        '''AVCMidSiteMercs@@ TXT_TITLE TXT_DESC
        '''AVCMidSiteTrainer@@ TXT_TITLE TXT_DESC
        '''AVCMidUnit@@ NAME_TXT
        '''AVCMidStackTemplate@@ NAME_TXT
        '''AVCMidSubRace@@ NAME_TXT
        '''A [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property StartTextKeywords() As String
            Get
                Return ResourceManager.GetString("StartTextKeywords", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to AVCScenarioInfo@@ NAME 64
        '''AVCScenarioInfo@@ DESC 254
        '''AVCScenarioInfo@@ BRIEFING 254
        '''AVCScenarioInfo@@ DEBUNKW 253
        '''AVCScenarioInfo@@ DEBUNKL 254
        '''AVCScenarioInfo@@ BRIEFLONG1 253
        '''AVCScenarioInfo@@ CREATOR 20
        '''AVCMidPlayer@@ NAME_TXT 15
        '''AVCCapital@@ NAME_TXT 20
        '''AVCMidVillage@@ NAME_TXT 20
        '''AVCMidRuin@@ TITLE 25
        '''AVCMidLandmark@@ DESC_TXT 254
        '''AVCMidSiteMerchant@@ TXT_TITLE 40
        '''AVCMidSiteMerchant@@ TXT_DESC 100
        '''AVCMidSiteMage@@ TXT_TITLE 40
        '''AVCMidSiteMage@@ TXT_DESC 100
        '''AVCMidSiteMercs@@ TXT_TITLE 40 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property TextMaxSize() As String
            Get
                Return ResourceManager.GetString("TextMaxSize", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
